# Generated by Django 6.1 on 2026-09-07 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('organisateur', 'Organisateur'), ('participant', 'Participant'), ('modérateur', 'Modérateur'), ('admin', 'Admin')], max_length=20),
        ),
    ]
