# Generated by Django 6.1 on 2026-09-07 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='adresse',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresse'),
        ),
        migrations.AddField(
            model_name='user',
            name='bith_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de naissance'),
        ),
        migrations.AlterField(
            model_name='user',
            name='civilite',
            field=models.CharField(choices=[('Homme', 'Mr'), ('Femme', 'Mme')], max_length=6),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('modérateur', 'Modérateur'), ('participant', 'Participant'), ('organisateur', 'Organisateur')], max_length=20),
        ),
    ]
