# Generated by Django 6.1 on 2026-09-12 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_adresse_user_bith_date_alter_user_civilite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tel',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Numéro de téléphone'),
        ),
    ]
