# Generated by Django 6.1 on 2026-09-12 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_user_tel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('modérateur', 'Modérateur'), ('participant', 'Participant'), ('organisateur', 'Organisateur')], max_length=20),
        ),
    ]
