# Generated by Django 6.1 on 2026-10-03 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='URL')),
                ('short_description', models.CharField(blank=True, max_length=255, verbose_name='Résumé')),
                ('description', models.TextField(verbose_name='Description')),
                ('category', models.CharField(choices=[('concert', 'Concert'), ('conference', 'Conférence'), ('festival', 'Festival'), ('sport', 'Sport'), ('theatre', 'Théâtre'), ('autre', 'Autre')], default='concert', max_length=30, verbose_name='Catégorie')),
                ('event_date', models.DateTimeField(verbose_name="Date de l'événement")),
                ('location', models.CharField(max_length=200, verbose_name='Lieu')),
                ('venue', models.CharField(blank=True, max_length=200, verbose_name='Salle / lieu précis')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Prix')),
                ('capacity', models.PositiveIntegerField(default=0, verbose_name='Capacité')),
                ('available_tickets', models.PositiveIntegerField(default=0, verbose_name='Tickets disponibles')),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/', verbose_name='Image')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publié')),
                ('status', models.CharField(choices=[('brouillon', 'Brouillon'), ('publie', 'Publié'), ('archive', 'Archivé')], default='publie', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organizer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organized_events', to=settings.AUTH_USER_MODEL, verbose_name='Organisateur')),
            ],
            options={
                'verbose_name': 'Événement',
                'verbose_name_plural': 'Événements',
                'ordering': ['-event_date'],
            },
        ),
    ]
